---
title: "Canine DUXC: Implications for DUX4 retrotransposition and preclinical models of FSHD"
author: "Chao-Jen Wong"
date: "`r Sys.Date()`"
documentclass: "book"
output:
  bookdown::gitbook:
    highlight: tango
site: bookdown::bookdown_site
bibliography: [journals.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Bioinformatics and statistics analysis"
---

# Preface {-}

We wrote this book to support the reproducibility and transparancy of the computational work for the manuscript, _Canine DUXC: Implications for DUX4 retrotransposition and preclinical models of FSHD_[insert line here]. This book is built by **R markdown**, **knitr** [@R-knitr], and **bookdown** [@bookdown2016] R packages. It presents the workflow and reproducible **R** code of our Bioinformatics analysis on the RNA-seq and ChIP-seq data, in which the processed data are available in our [GitHub repos](https://github.com/FredHutch/canFam3.DuxFamily). All the figures and tables in the book are rendered by the [book source Rmd files](https://github.com/FredHutch/canFam3.DuxFamily/tree/master/gitbook) on the fly. 

Note that some of the code might be tedious and therefore are hidden from the display, but they are can be found in the [source files](https://github.com/FredHutch/canFam3.DuxFamily/tree/master/gitbook)

## Datasets

The repository's [data](https://github.com/FredHutch/canFam3.DuxFamily/tree/master/data) foler include RNA-seq read counts (`DESeqDataSet`) as well as the ChIP-seq peaks calling results (`GRanges`). 

- canine RNA-seq (GSE188928): DUX4, DUXC, and DUX-ALT transcriptome in canine skeletal muscle and repeat element expression
```
├── CALTinC.ens.dds.rda: DUXC-ALT transcriptome in canine skeletal muscle
├── CALTinC_rmsk.rda: repeat element expression in DUXC-ALT transcriptome
├── CinC.ens.dds.rda: DUXC transcriptome
├── CinC_rmsk.rda: DUXC repeat element expression
├── HinC.ens.dds.rda: DUX4 transcriptome in canine skeletal muscle
├── HinC_rmsk.rda: repeat element expression in HinC transcriptome
```

- human DUX4 transcriptome in human myblast([GSE85461](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE85461)) and mouse Dux transcriptome in mouse myblast cell lines ([GSE87282](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE87282))     
```
├── C2C12.ens.ddsl2.rda: Dux and DUX4 transcriptome in mouse myoblast cell lines
├── HinH.ens.dds.rda: DUX4 transcriptome in human myoblast
├── HinH_rmsk.rda: repeat element expression in HinH transcriptome
```

- miscellaneous. The orthologous are collected from Ensembl ortholog database V88.   
```
├── human_cleavage.rda: Hendrikson 2017 zygotic activation gene set
├── canine_human_mouse_ensOrtholog.rda: human-canine and mouse-canine paired orthologous
├── human_mouse_ensOrtholog.rda: human-mouse paired Ortholog
├── peaks_list.rda: ChIP-seq peaks 
├── chipseq_si.rda: ChIP-seq sample information
└── z4_ensembl.rda: Akiyama 2015 2C-like gene set from 
```

## Annotation

### canFam3 ensembl GTF
We used Bioconductor's _AnnotationHub_ package to extract canFam3 ensembl's GTF file and built a `TxDb` (transcript database) annotation package. 
```{r build-TxDb-pkg, eval=FALSE}
# example:
library(AnnotationHub)
ah = AnnotationHub()
query(ah, c("canFam3", "ensembl"))
gr <- ah["AH79003"] ## download Canis_familiaris ensembl version 99
## (1) build on the fly
txdb <- makeTxDbFromGRanges(gr)  ## build on the fly
## (2) build a package
md <- 
  data.frame(name=c("ensembl_version", "Data source", 
                    "Organism", "Resource URL", "Type of Gene ID"),
             value=c("canFam3.1.99", "AnnotationHub query AH79003", 
                     "Canis familiaris ", "http://ensembl.org", 
                     "Ensembl Gene ID"))
txdb <- makeTxDbFromGRanges(gr, metadata=md)
makeTxDbPackage(txdb=txdb, version="1.0.0",
                pkgname="TxDb.Cfamiliaris.CanFam3.ensGene",
                maintainer="Chao-Jen Wong <cwon2@fredhutch.org>",
                author="Chao-Jen Wong",
                destDir="~/tapscott/canfam3")
```

## Software
R/3.6.3 and Bioconductor v3.10